#!/usr/bin/env bash
# Builds the simulation to WebAssembly and emits it as src/wasm.ts.
#
# The module is inlined as base64 rather than shipped as a separate .wasm file.
# It costs about 680 bytes gzipped, and buys a package that needs no asset
# hosted, no path configured and no second request — `npm i` is the whole
# integration. That trade is right at 4KB and would be indefensible at 200KB.
#
# The result is committed, so neither CI nor a consumer needs a Rust toolchain.
# Rerun this whenever src/lib.rs changes and commit the result alongside it.
set -euo pipefail

cd "$(dirname "$0")"

cargo build --release --target wasm32-unknown-unknown

wasm=target/wasm32-unknown-unknown/release/particles.wasm
out=../../src/wasm.ts

{
  printf '/* Generated by crates/particles/build.sh. Do not edit.\n'
  printf '\n'
  printf '   The compiled simulation, inlined so the package ships as one file.\n'
  printf '   Rebuild with `pnpm wasm` after changing the crate. */\n'
  printf '\n'
  # Annotated `: string` rather than left to inference. Without it TypeScript
  # types the constant as the base64 literal, and ships the whole payload again
  # inside the .d.ts.
  printf 'const wasm: string =\n'
  printf "  '%s';\n" "$(base64 < "$wasm" | tr -d '\n')"
  printf '\n'
  printf 'export { wasm };\n'
} > "$out"

printf '%s  %s bytes of wasm, %s bytes of base64 (%s gzipped)\n' \
  "$out" \
  "$(wc -c < "$wasm" | tr -d ' ')" \
  "$(wc -c < "$out" | tr -d ' ')" \
  "$(gzip -9c "$out" | wc -c | tr -d ' ')"
